// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bids/v1/bid_service.proto

package bidsv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1 "github.com/floroz/gavel/pkg/proto/bids/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BidServiceName is the fully-qualified name of the BidService service.
	BidServiceName = "bids.v1.BidService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BidServicePlaceBidProcedure is the fully-qualified name of the BidService's PlaceBid RPC.
	BidServicePlaceBidProcedure = "/bids.v1.BidService/PlaceBid"
)

// BidServiceClient is a client for the bids.v1.BidService service.
type BidServiceClient interface {
	PlaceBid(context.Context, *connect.Request[v1.PlaceBidRequest]) (*connect.Response[v1.PlaceBidResponse], error)
}

// NewBidServiceClient constructs a client for the bids.v1.BidService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBidServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BidServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bidServiceMethods := v1.File_bids_v1_bid_service_proto.Services().ByName("BidService").Methods()
	return &bidServiceClient{
		placeBid: connect.NewClient[v1.PlaceBidRequest, v1.PlaceBidResponse](
			httpClient,
			baseURL+BidServicePlaceBidProcedure,
			connect.WithSchema(bidServiceMethods.ByName("PlaceBid")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bidServiceClient implements BidServiceClient.
type bidServiceClient struct {
	placeBid *connect.Client[v1.PlaceBidRequest, v1.PlaceBidResponse]
}

// PlaceBid calls bids.v1.BidService.PlaceBid.
func (c *bidServiceClient) PlaceBid(ctx context.Context, req *connect.Request[v1.PlaceBidRequest]) (*connect.Response[v1.PlaceBidResponse], error) {
	return c.placeBid.CallUnary(ctx, req)
}

// BidServiceHandler is an implementation of the bids.v1.BidService service.
type BidServiceHandler interface {
	PlaceBid(context.Context, *connect.Request[v1.PlaceBidRequest]) (*connect.Response[v1.PlaceBidResponse], error)
}

// NewBidServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBidServiceHandler(svc BidServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bidServiceMethods := v1.File_bids_v1_bid_service_proto.Services().ByName("BidService").Methods()
	bidServicePlaceBidHandler := connect.NewUnaryHandler(
		BidServicePlaceBidProcedure,
		svc.PlaceBid,
		connect.WithSchema(bidServiceMethods.ByName("PlaceBid")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bids.v1.BidService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BidServicePlaceBidProcedure:
			bidServicePlaceBidHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBidServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBidServiceHandler struct{}

func (UnimplementedBidServiceHandler) PlaceBid(context.Context, *connect.Request[v1.PlaceBidRequest]) (*connect.Response[v1.PlaceBidResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bids.v1.BidService.PlaceBid is not implemented"))
}
