// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file bids/v1/bid_service.proto (package bids.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PlaceBidRequest, PlaceBidResponse } from "./bid_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bids.v1.BidService
 */
export const BidService = {
  typeName: "bids.v1.BidService",
  methods: {
    /**
     * @generated from rpc bids.v1.BidService.PlaceBid
     */
    placeBid: {
      name: "PlaceBid",
      I: PlaceBidRequest,
      O: PlaceBidResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

