// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file bids/v1/bid_service.proto (package bids.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message bids.v1.PlaceBidRequest
 */
export class PlaceBidRequest extends Message<PlaceBidRequest> {
  /**
   * @generated from field: string item_id = 1;
   */
  itemId = "";

  /**
   * @generated from field: string user_id = 2;
   */
  userId = "";

  /**
   * @generated from field: int64 amount = 3;
   */
  amount = protoInt64.zero;

  constructor(data?: PartialMessage<PlaceBidRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bids.v1.PlaceBidRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "item_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaceBidRequest {
    return new PlaceBidRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaceBidRequest {
    return new PlaceBidRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaceBidRequest {
    return new PlaceBidRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PlaceBidRequest | PlainMessage<PlaceBidRequest> | undefined, b: PlaceBidRequest | PlainMessage<PlaceBidRequest> | undefined): boolean {
    return proto3.util.equals(PlaceBidRequest, a, b);
  }
}

/**
 * @generated from message bids.v1.PlaceBidResponse
 */
export class PlaceBidResponse extends Message<PlaceBidResponse> {
  /**
   * @generated from field: bids.v1.Bid bid = 1;
   */
  bid?: Bid;

  constructor(data?: PartialMessage<PlaceBidResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bids.v1.PlaceBidResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bid", kind: "message", T: Bid },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaceBidResponse {
    return new PlaceBidResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaceBidResponse {
    return new PlaceBidResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaceBidResponse {
    return new PlaceBidResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PlaceBidResponse | PlainMessage<PlaceBidResponse> | undefined, b: PlaceBidResponse | PlainMessage<PlaceBidResponse> | undefined): boolean {
    return proto3.util.equals(PlaceBidResponse, a, b);
  }
}

/**
 * @generated from message bids.v1.Bid
 */
export class Bid extends Message<Bid> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string item_id = 2;
   */
  itemId = "";

  /**
   * @generated from field: string user_id = 3;
   */
  userId = "";

  /**
   * @generated from field: int64 amount = 4;
   */
  amount = protoInt64.zero;

  /**
   * ISO 8601 string
   *
   * @generated from field: string created_at = 5;
   */
  createdAt = "";

  constructor(data?: PartialMessage<Bid>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bids.v1.Bid";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "item_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "created_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Bid {
    return new Bid().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Bid {
    return new Bid().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Bid {
    return new Bid().fromJsonString(jsonString, options);
  }

  static equals(a: Bid | PlainMessage<Bid> | undefined, b: Bid | PlainMessage<Bid> | undefined): boolean {
    return proto3.util.equals(Bid, a, b);
  }
}

