// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: userstats/v1/user_stats_service.proto

package userstatsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_userstats_v1_user_stats_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userstats_v1_user_stats_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_userstats_v1_user_stats_service_proto_rawDescGZIP(), []int{0}
}

type UserStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *UserStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsResponse) Reset() {
	*x = UserStatsResponse{}
	mi := &file_userstats_v1_user_stats_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResponse) ProtoMessage() {}

func (x *UserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userstats_v1_user_stats_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResponse.ProtoReflect.Descriptor instead.
func (*UserStatsResponse) Descriptor() ([]byte, []int) {
	return file_userstats_v1_user_stats_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatsResponse) GetStats() *UserStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalBids     int64                  `protobuf:"varint,2,opt,name=total_bids,json=totalBids,proto3" json:"total_bids,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`        // Total value of bids placed
	LastUpdatedAt string                 `protobuf:"bytes,4,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"` // ISO 8601 string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_userstats_v1_user_stats_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_userstats_v1_user_stats_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_userstats_v1_user_stats_service_proto_rawDescGZIP(), []int{2}
}

func (x *UserStats) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStats) GetTotalBids() int64 {
	if x != nil {
		return x.TotalBids
	}
	return 0
}

func (x *UserStats) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *UserStats) GetLastUpdatedAt() string {
	if x != nil {
		return x.LastUpdatedAt
	}
	return ""
}

var File_userstats_v1_user_stats_service_proto protoreflect.FileDescriptor

const file_userstats_v1_user_stats_service_proto_rawDesc = "" +
	"\n" +
	"%userstats/v1/user_stats_service.proto\x12\fuserstats.v1\"\x15\n" +
	"\x13GetUserStatsRequest\"B\n" +
	"\x11UserStatsResponse\x12-\n" +
	"\x05stats\x18\x01 \x01(\v2\x17.userstats.v1.UserStatsR\x05stats\"\x8e\x01\n" +
	"\tUserStats\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"total_bids\x18\x02 \x01(\x03R\ttotalBids\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12&\n" +
	"\x0flast_updated_at\x18\x04 \x01(\tR\rlastUpdatedAt2f\n" +
	"\x10UserStatsService\x12R\n" +
	"\fGetUserStats\x12!.userstats.v1.GetUserStatsRequest\x1a\x1f.userstats.v1.UserStatsResponseB<Z:github.com/floroz/gavel/pkg/proto/userstats/v1;userstatsv1b\x06proto3"

var (
	file_userstats_v1_user_stats_service_proto_rawDescOnce sync.Once
	file_userstats_v1_user_stats_service_proto_rawDescData []byte
)

func file_userstats_v1_user_stats_service_proto_rawDescGZIP() []byte {
	file_userstats_v1_user_stats_service_proto_rawDescOnce.Do(func() {
		file_userstats_v1_user_stats_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userstats_v1_user_stats_service_proto_rawDesc), len(file_userstats_v1_user_stats_service_proto_rawDesc)))
	})
	return file_userstats_v1_user_stats_service_proto_rawDescData
}

var file_userstats_v1_user_stats_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_userstats_v1_user_stats_service_proto_goTypes = []any{
	(*GetUserStatsRequest)(nil), // 0: userstats.v1.GetUserStatsRequest
	(*UserStatsResponse)(nil),   // 1: userstats.v1.UserStatsResponse
	(*UserStats)(nil),           // 2: userstats.v1.UserStats
}
var file_userstats_v1_user_stats_service_proto_depIdxs = []int32{
	2, // 0: userstats.v1.UserStatsResponse.stats:type_name -> userstats.v1.UserStats
	0, // 1: userstats.v1.UserStatsService.GetUserStats:input_type -> userstats.v1.GetUserStatsRequest
	1, // 2: userstats.v1.UserStatsService.GetUserStats:output_type -> userstats.v1.UserStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_userstats_v1_user_stats_service_proto_init() }
func file_userstats_v1_user_stats_service_proto_init() {
	if File_userstats_v1_user_stats_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userstats_v1_user_stats_service_proto_rawDesc), len(file_userstats_v1_user_stats_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userstats_v1_user_stats_service_proto_goTypes,
		DependencyIndexes: file_userstats_v1_user_stats_service_proto_depIdxs,
		MessageInfos:      file_userstats_v1_user_stats_service_proto_msgTypes,
	}.Build()
	File_userstats_v1_user_stats_service_proto = out.File
	file_userstats_v1_user_stats_service_proto_goTypes = nil
	file_userstats_v1_user_stats_service_proto_depIdxs = nil
}
