// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file userstats/v1/user_stats_service.proto (package userstats.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message userstats.v1.GetUserStatsRequest
 */
export class GetUserStatsRequest extends Message<GetUserStatsRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<GetUserStatsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "userstats.v1.GetUserStatsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserStatsRequest {
    return new GetUserStatsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserStatsRequest {
    return new GetUserStatsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserStatsRequest {
    return new GetUserStatsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserStatsRequest | PlainMessage<GetUserStatsRequest> | undefined, b: GetUserStatsRequest | PlainMessage<GetUserStatsRequest> | undefined): boolean {
    return proto3.util.equals(GetUserStatsRequest, a, b);
  }
}

/**
 * @generated from message userstats.v1.UserStatsResponse
 */
export class UserStatsResponse extends Message<UserStatsResponse> {
  /**
   * @generated from field: userstats.v1.UserStats stats = 1;
   */
  stats?: UserStats;

  constructor(data?: PartialMessage<UserStatsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "userstats.v1.UserStatsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stats", kind: "message", T: UserStats },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserStatsResponse {
    return new UserStatsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserStatsResponse {
    return new UserStatsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserStatsResponse {
    return new UserStatsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UserStatsResponse | PlainMessage<UserStatsResponse> | undefined, b: UserStatsResponse | PlainMessage<UserStatsResponse> | undefined): boolean {
    return proto3.util.equals(UserStatsResponse, a, b);
  }
}

/**
 * @generated from message userstats.v1.UserStats
 */
export class UserStats extends Message<UserStats> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: int64 total_bids = 2;
   */
  totalBids = protoInt64.zero;

  /**
   * Total value of bids placed
   *
   * @generated from field: int64 total_amount = 3;
   */
  totalAmount = protoInt64.zero;

  /**
   * ISO 8601 string
   *
   * @generated from field: string last_updated_at = 4;
   */
  lastUpdatedAt = "";

  constructor(data?: PartialMessage<UserStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "userstats.v1.UserStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "total_bids", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "total_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "last_updated_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserStats {
    return new UserStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserStats {
    return new UserStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserStats {
    return new UserStats().fromJsonString(jsonString, options);
  }

  static equals(a: UserStats | PlainMessage<UserStats> | undefined, b: UserStats | PlainMessage<UserStats> | undefined): boolean {
    return proto3.util.equals(UserStats, a, b);
  }
}

