// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file userstats/v1/user_stats_service.proto (package userstats.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserStatsRequest, UserStatsResponse } from "./user_stats_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service userstats.v1.UserStatsService
 */
export const UserStatsService = {
  typeName: "userstats.v1.UserStatsService",
  methods: {
    /**
     * @generated from rpc userstats.v1.UserStatsService.GetUserStats
     */
    getUserStats: {
      name: "GetUserStats",
      I: GetUserStatsRequest,
      O: UserStatsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

