// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: userstats/v1/user_stats_service.proto

package userstatsv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"

	v1 "github.com/floroz/gavel/pkg/proto/userstats/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserStatsServiceName is the fully-qualified name of the UserStatsService service.
	UserStatsServiceName = "userstats.v1.UserStatsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserStatsServiceGetUserStatsProcedure is the fully-qualified name of the UserStatsService's
	// GetUserStats RPC.
	UserStatsServiceGetUserStatsProcedure = "/userstats.v1.UserStatsService/GetUserStats"
)

// UserStatsServiceClient is a client for the userstats.v1.UserStatsService service.
type UserStatsServiceClient interface {
	GetUserStats(context.Context, *connect.Request[v1.GetUserStatsRequest]) (*connect.Response[v1.UserStatsResponse], error)
}

// NewUserStatsServiceClient constructs a client for the userstats.v1.UserStatsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserStatsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserStatsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userStatsServiceMethods := v1.File_userstats_v1_user_stats_service_proto.Services().ByName("UserStatsService").Methods()
	return &userStatsServiceClient{
		getUserStats: connect.NewClient[v1.GetUserStatsRequest, v1.UserStatsResponse](
			httpClient,
			baseURL+UserStatsServiceGetUserStatsProcedure,
			connect.WithSchema(userStatsServiceMethods.ByName("GetUserStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userStatsServiceClient implements UserStatsServiceClient.
type userStatsServiceClient struct {
	getUserStats *connect.Client[v1.GetUserStatsRequest, v1.UserStatsResponse]
}

// GetUserStats calls userstats.v1.UserStatsService.GetUserStats.
func (c *userStatsServiceClient) GetUserStats(ctx context.Context, req *connect.Request[v1.GetUserStatsRequest]) (*connect.Response[v1.UserStatsResponse], error) {
	return c.getUserStats.CallUnary(ctx, req)
}

// UserStatsServiceHandler is an implementation of the userstats.v1.UserStatsService service.
type UserStatsServiceHandler interface {
	GetUserStats(context.Context, *connect.Request[v1.GetUserStatsRequest]) (*connect.Response[v1.UserStatsResponse], error)
}

// NewUserStatsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserStatsServiceHandler(svc UserStatsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userStatsServiceMethods := v1.File_userstats_v1_user_stats_service_proto.Services().ByName("UserStatsService").Methods()
	userStatsServiceGetUserStatsHandler := connect.NewUnaryHandler(
		UserStatsServiceGetUserStatsProcedure,
		svc.GetUserStats,
		connect.WithSchema(userStatsServiceMethods.ByName("GetUserStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/userstats.v1.UserStatsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserStatsServiceGetUserStatsProcedure:
			userStatsServiceGetUserStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserStatsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserStatsServiceHandler struct{}

func (UnimplementedUserStatsServiceHandler) GetUserStats(context.Context, *connect.Request[v1.GetUserStatsRequest]) (*connect.Response[v1.UserStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("userstats.v1.UserStatsService.GetUserStats is not implemented"))
}
