// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: bids/v1/bid_service.proto

package bidsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_bids_v1_bid_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bids_v1_bid_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_bids_v1_bid_service_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceBidRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PlaceBidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlaceBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           *Bid                   `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	mi := &file_bids_v1_bid_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bids_v1_bid_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_bids_v1_bid_service_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBidResponse) GetBid() *Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_bids_v1_bid_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_bids_v1_bid_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_bids_v1_bid_service_proto_rawDescGZIP(), []int{2}
}

func (x *Bid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bid) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Bid) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bid) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bid) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_bids_v1_bid_service_proto protoreflect.FileDescriptor

const file_bids_v1_bid_service_proto_rawDesc = "" +
	"\n" +
	"\x19bids/v1/bid_service.proto\x12\abids.v1\"B\n" +
	"\x0fPlaceBidRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"2\n" +
	"\x10PlaceBidResponse\x12\x1e\n" +
	"\x03bid\x18\x01 \x01(\v2\f.bids.v1.BidR\x03bid\"~\n" +
	"\x03Bid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2M\n" +
	"\n" +
	"BidService\x12?\n" +
	"\bPlaceBid\x12\x18.bids.v1.PlaceBidRequest\x1a\x19.bids.v1.PlaceBidResponseB2Z0github.com/floroz/gavel/pkg/proto/bids/v1;bidsv1b\x06proto3"

var (
	file_bids_v1_bid_service_proto_rawDescOnce sync.Once
	file_bids_v1_bid_service_proto_rawDescData []byte
)

func file_bids_v1_bid_service_proto_rawDescGZIP() []byte {
	file_bids_v1_bid_service_proto_rawDescOnce.Do(func() {
		file_bids_v1_bid_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bids_v1_bid_service_proto_rawDesc), len(file_bids_v1_bid_service_proto_rawDesc)))
	})
	return file_bids_v1_bid_service_proto_rawDescData
}

var file_bids_v1_bid_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bids_v1_bid_service_proto_goTypes = []any{
	(*PlaceBidRequest)(nil),  // 0: bids.v1.PlaceBidRequest
	(*PlaceBidResponse)(nil), // 1: bids.v1.PlaceBidResponse
	(*Bid)(nil),              // 2: bids.v1.Bid
}
var file_bids_v1_bid_service_proto_depIdxs = []int32{
	2, // 0: bids.v1.PlaceBidResponse.bid:type_name -> bids.v1.Bid
	0, // 1: bids.v1.BidService.PlaceBid:input_type -> bids.v1.PlaceBidRequest
	1, // 2: bids.v1.BidService.PlaceBid:output_type -> bids.v1.PlaceBidResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bids_v1_bid_service_proto_init() }
func file_bids_v1_bid_service_proto_init() {
	if File_bids_v1_bid_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bids_v1_bid_service_proto_rawDesc), len(file_bids_v1_bid_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bids_v1_bid_service_proto_goTypes,
		DependencyIndexes: file_bids_v1_bid_service_proto_depIdxs,
		MessageInfos:      file_bids_v1_bid_service_proto_msgTypes,
	}.Build()
	File_bids_v1_bid_service_proto = out.File
	file_bids_v1_bid_service_proto_goTypes = nil
	file_bids_v1_bid_service_proto_depIdxs = nil
}
